"""What the integration of the review fixes added where two buckets met.

* A session that fails reads as FAILED only once it has released everything: the planner closed, the
  human executors closed, the merges waited for. `tandem collect` exits as soon as a session has
  ended, and a failure marked first let it exit under all of that.
* The trajectory says which planner recorded it, and what it was asked, even when the planner's leg
  does not: `tandem traj open` picks the viewer by the first.
* TiPToP's rendered config is dumped through a fresh YAML instance, and never truncated by a dump
  that fails.
* doctor says, before anyone is at the robot, that an SDK planner with no ``capture_frame`` will be
  refused by a session whose checks need a frame.
"""

from __future__ import annotations

import json

import pytest
from fake_backend import FakeBackend
from helpers import isolate_registry, use_fake_backend, wait_for

from tandem.core import episodes, secrets
from tandem.core.session import Session, State

# --- a failing session ends last ------------------------------------------------------------------


def test_a_failing_session_reads_as_failed_only_once_everything_is_released(profile, monkeypatch):
    monkeypatch.setattr(secrets, "gemini_api_key", lambda: "test-key")

    class WontWarm(FakeBackend):
        def warm(self) -> None:
            raise RuntimeError("the arm is not answering")

    built = use_fake_backend(monkeypatch, backend_type=WontWarm)
    session = Session(profile, task="pick up the block")
    seen: list[tuple[str, bool]] = []
    session.subscribe(
        lambda e: seen.append((e["state"], built[-1].closed)) if e.get("type") == "state" and built else None
    )
    session.start()
    assert wait_for(lambda: not session.alive), f"stuck in {session.state}"

    assert session.state is State.FAILED and "the arm is not answering" in (session.error or "")
    failed = [closed for state, closed in seen if state == State.FAILED.value]
    assert failed == [True], "the session read as failed before the planner was closed"
    assert State.STOPPED.value not in [state for state, _ in seen]


# --- who recorded the trajectory ------------------------------------------------------------------


def _leg(tmp_path, **meta):
    leg = tmp_path / "leg"
    leg.mkdir()
    (leg / "_meta.json").write_text(json.dumps({"trajectory_id": "t" * 16, **meta}))
    return leg


def _meta(leg):
    return json.loads((leg / "_meta.json").read_text())


def test_the_primary_leg_is_stamped_with_its_planner_and_instruction(tmp_path):
    leg = _leg(tmp_path, source="tamp")
    episodes.stamp_primary_meta(leg, planner="toy", instruction="put the apple in the bin", log=print)
    meta = _meta(leg)
    assert (meta["planner"], meta["instruction"]) == ("toy", "put the apple in the bin")
    assert meta["trajectory_id"] == "t" * 16


def test_what_the_planner_wrote_stands(tmp_path):
    leg = _leg(tmp_path, planner="tiptop", instruction="as the planner had it")
    episodes.stamp_primary_meta(leg, planner="toy", instruction="the session's words", log=print)
    assert (_meta(leg)["planner"], _meta(leg)["instruction"]) == ("tiptop", "as the planner had it")


def test_a_persons_leg_is_never_stamped_as_a_planners(tmp_path):
    leg = _leg(tmp_path, source="teleop")
    episodes.stamp_primary_meta(leg, planner="toy", instruction="open the box", log=print)
    assert "planner" not in _meta(leg) and _meta(leg)["instruction"] == "open the box"


def test_an_unreadable_meta_costs_the_stamp_and_nothing_else(tmp_path):
    leg = tmp_path / "leg"
    leg.mkdir()
    (leg / "_meta.json").write_text("{not json")
    episodes.stamp_primary_meta(leg, planner="toy", instruction="x", log=print)
    assert (leg / "_meta.json").read_text() == "{not json"
    episodes.stamp_primary_meta(None, planner="toy", instruction="x", log=print)


def test_traj_open_reads_the_stamp_before_the_profile(tmp_path, profile):
    from types import SimpleNamespace

    from tandem.cli import traj as traj_cli

    leg = _leg(tmp_path, source="tamp")
    episodes.stamp_primary_meta(leg, planner="someone-else", instruction=None, log=print)
    planner, how = traj_cli.recorded_by(SimpleNamespace(path=leg, meta=_meta(leg)), profile)
    assert planner == "someone-else" and "_meta.json" in how


# --- TiPToP's rendered config ---------------------------------------------------------------------


def test_a_render_that_fails_leaves_the_last_config_and_the_next_one_writes(tmp_path, profile, monkeypatch):
    from ruamel.yaml.error import YAMLError

    from tandem.planners.tiptop import render

    dest = tmp_path / "tiptop.yml"
    render.write_tiptop_config(profile, dest)
    good = dest.read_text()
    assert "Generated by tandem" in good and len(good.splitlines()) > 3

    real = render.render_tiptop_config
    # A value YAML cannot represent: the dump raises part-way.
    monkeypatch.setattr(render, "render_tiptop_config", lambda *a, **k: {"bad": object()})
    with pytest.raises(YAMLError):
        render.write_tiptop_config(profile, dest)
    assert dest.read_text() == good, "a failed dump truncated the last good config"

    monkeypatch.setattr(render, "render_tiptop_config", real)
    render.write_tiptop_config(profile, dest)
    assert dest.read_text() == good, "a dump after a failed one wrote something else"


# --- doctor on a planner that cannot capture a frame ---------------------------------------------


@pytest.fixture
def sdk_planners(monkeypatch):
    from toy_planner import ToyPlanner

    from tandem.planners import registry
    from tandem.planners.sdk import Planner

    isolate_registry(monkeypatch)

    class Blind(ToyPlanner):
        capture_frame = Planner.capture_frame

    registry.register_backend("toy", ToyPlanner, replace=True)
    registry.register_backend("toy-blind", _renamed(Blind, "toy-blind"), replace=True)
    return registry


def _renamed(cls, name):
    from dataclasses import replace

    cls.info = replace(cls.info, name=name)
    cls.CAPABILITIES = replace(cls.CAPABILITIES, name=name)
    return cls


def test_doctor_names_the_checks_a_blind_planner_cannot_serve(sdk_planners, profile):
    from tandem.cli import doctor

    hitl = profile.hitl.model_copy(update={"check_human_effects": True, "check_tamp_effects": False})
    assert doctor._frame_checks_unanswerable("toy-blind", hitl) == ["check_human_effects"]
    assert doctor._frame_checks_unanswerable("toy", hitl) == []
    off = hitl.model_copy(update={"check_human_effects": False, "check_human_preconditions": False})
    assert doctor._frame_checks_unanswerable("toy-blind", off) == []


def test_doctor_fails_the_phase_planning_row_for_a_blind_planner(sdk_planners, profile, monkeypatch):
    from tandem.cli import doctor
    from tandem.core import probe

    monkeypatch.setattr(secrets, "gemini_api_key", lambda: "test-key")
    profile.planner = profile.planner.model_copy(update={"backend": "toy-blind", "options": {}})
    profile.hitl.enabled = True
    profile.hitl.check_human_effects = True
    row = doctor._phase_planning_check(profile)
    assert row.state == probe.FAIL and "cannot capture a camera frame" in row.detail
    assert "hitl.check_human_effects" in row.detail
