"""Profile and TiPToP's options → the three things a tiptop subprocess actually consumes.

    render_tiptop_config(profile)   -> the YAML tiptop_cfg() loads   ($TIPTOP_CONFIG)
    render_tamp_overrides(profile)  -> the JSON --curobo-overrides reads
    render_env(profile, ...)        -> the environment the child runs in

Keeping this in one small, unit-testable module is deliberate: it is the seam where a
profile stops being tandem's concern and becomes tiptop's, and it is where "did my override
actually apply?" is decided.

Every function takes the profile -- for the task, the cameras and the calibration, which are
tandem's -- and ``options``, TiPToP's own settings (``options.TiptopOptions``). Left out, they are
the profile's ``planner.options``; the factory passes the ones the session handed it.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from ruamel.yaml import YAML

from tandem.core import paths, profiles, secrets
from tandem.core.errors import ProfileError
from tandem.core.profiles import Profile
from tandem.planners.tiptop import tamp_keys
from tandem.planners.tiptop.options import DETECTOR_MODEL, TiptopOptions, options_of, parse

_yaml = YAML()
_yaml.default_flow_style = False

# How check_assets starts the two problems that stop a session before it starts, rather than warn:
# a camera with no extrinsics, and a camera the pinned tiptop opens that the profile does not have.
# The factory refuses on either; doctor shows each as a FAIL row of its own.
MISSING_EXTRINSICS = "no camera extrinsics"
MISSING_CAMERA = "no cameras."


# --------------------------------------------------------------------------- tiptop.yml


def _options(profile: Profile, options: Any) -> TiptopOptions:
    return options_of(profile) if options is None else parse(options)


def render_tiptop_config(profile: Profile, options: Any = None) -> dict:
    """The dict tiptop's ``tiptop_cfg()`` expects (robot / cameras / perception).

    The perception knobs a ``tamp:`` block may set (``tamp_keys.PERCEPTION_KEYS``: M2T2's grasp
    threshold and pass count, the voxel size, the contact threshold) are written where tiptop reads
    them -- ``perception.m2t2.num_runs`` and ``perception.m2t2.grasp_threshold`` for the M2T2 pair
    (perception_wrapper.predict_depth_and_grasps) -- overriding the profile's ``perception:`` value
    where both are set, as tiptop's own override does. Unset, they are left out, so tiptop's own
    defaults (5 passes, 0.035) apply rather than a copy of them that could go stale.
    """
    p = profile
    o = _options(profile, options)
    cameras: dict[str, Any] = {"perception": p.cameras.perception}
    for key, cam in p.cameras.configured().items():
        cameras[key] = {
            "serial": cam.serial,
            "type": cam.type,
            "resolution": cam.resolution,
            "fps": cam.fps,
        }

    rendered = {
        "robot": {
            "type": o.robot.type,
            "dof": o.robot.dof,
            "host": o.robot.host,
            "port": o.robot.port,
            "gripper_port": o.robot.gripper_port,
            "time_dilation_factor": o.robot.time_dilation_factor,
            "q_home": list(o.robot.q_home),
            "q_capture": list(o.robot.q_capture),
        },
        "cameras": cameras,
        "perception": {
            # Unused since depth comes from the ZED's hardware stereo, but tiptop still reads
            # the key, so it stays for config compatibility.
            "foundation_stereo": {"url": "http://localhost:1234"},
            "m2t2": {
                "url": o.perception.m2t2.url,
                "apply_bounds": o.perception.m2t2.apply_bounds,
            },
            # tiptop reads sam.url whenever the mode is not "local"; the options refuse a remote
            # mode without one.
            "sam": {
                "mode": o.perception.sam_mode,
                **({"url": o.perception.sam_url} if o.perception.sam_url else {}),
            },
            "robot_mask_margin_m": o.perception.robot_mask_margin_m,
            "depth_trunc_m": o.perception.depth_trunc_m,
            "voxel_downsample_size": o.perception.voxel_downsample_size,
            "contact_threshold_m": o.perception.contact_threshold_m,
            "mask_erosion_pixels": o.perception.mask_erosion_pixels,
            "depth_smoothing": {"num_frames": o.perception.depth_smoothing_frames},
        },
    }
    for key, path in tamp_keys.PERCEPTION_KEYS.items():
        if key in o.tamp:
            node = rendered
            for part in path[:-1]:
                node = node.setdefault(part, {})
            node[path[-1]] = o.tamp[key]
    return rendered


def write_tiptop_config(profile: Profile, dest: Path, options: Any = None) -> Path:
    dest.parent.mkdir(parents=True, exist_ok=True)
    with dest.open("w") as fh:
        fh.write("# Generated by tandem from the profile — edits here are overwritten.\n")
        _yaml.dump(render_tiptop_config(profile, options), fh)
    return dest


# --------------------------------------------------------------------------- overrides


def render_tamp_overrides(profile: Profile, options: Any = None, *, runtime_dir: Path | None = None) -> dict:
    """The flat dict of solver-cost knobs the planner backend is built with.

    Path-valued knobs are resolved to absolute paths here rather than left for tiptop to
    interpret against a repo root, so "relative" means "relative to the profile" — the only
    reading a profile author can reasonably expect.
    """
    out: dict[str, Any] = dict(_options(profile, options).tamp)
    for key in tamp_keys.PATH_KEYS:
        if key in out:
            out[key] = str(_resolve_asset(profile, str(out[key]), key, runtime_dir))
    return out


def _resolve_asset(profile: Profile, value: str, key: str, runtime_dir: Path | None) -> Path:
    """Resolve a checkpoint path: absolute wins, then the profile dir, then the runtime dir.

    The runtime dir is included because TiPToP's runtime recipe puts the DATAFARM checkpoints there
    under the same relative layout the source monorepo used (vae/checkpoints/...,
    rnd/checkpoints/...), so an imported legacy config keeps working unchanged.
    """
    candidate = Path(os.path.expanduser(value))
    if candidate.is_absolute():
        return candidate
    for base in filter(None, (profile.dir(), runtime_dir)):
        resolved = base / candidate
        if resolved.exists():
            return resolved.resolve()
    # Nothing on disk yet. Return the profile-relative interpretation so the error message
    # names the place the user most likely meant.
    return profiles.resolve_path(profile, value)


def write_tamp_overrides(
    profile: Profile, dest: Path, options: Any = None, *, runtime_dir: Path | None = None
) -> Path | None:
    """Write the overrides JSON, or return None when the profile sets nothing.

    Returning None matters: passing an empty --curobo-overrides is not the same as passing
    none, and we want stock behaviour to be exactly stock.
    """
    overrides = render_tamp_overrides(profile, options, runtime_dir=runtime_dir)
    if not overrides:
        return None
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(overrides, indent=2, sort_keys=True) + "\n")
    return dest


def check_assets(profile: Profile, options: Any = None, *, runtime_dir: Path | None = None) -> list[str]:
    """Problems that would only surface minutes into a warmed session. Cheap to check now.

    The VAE manifold cost torch.loads its checkpoint lazily, so a missing file does not fail
    until the first plan — after cuRobo, SAM2 and the cameras have all warmed up.
    """
    problems: list[str] = []
    o = _options(profile, options)
    tamp = o.tamp

    if tamp.get("vae_manifold_weight") and tamp.get("vae_path"):
        path = _resolve_asset(profile, str(tamp["vae_path"]), "vae_path", runtime_dir)
        if not path.is_file():
            problems.append(f"vae_manifold_weight is set but vae_path does not exist: {path}")

    if str(tamp.get("blend_mode", "")).lower() == "flow":
        raw = tamp.get("blend_model_path")
        if raw:
            path = _resolve_asset(profile, str(raw), "blend_model_path", runtime_dir)
            if not path.is_file():
                problems.append(f"blend_mode is 'flow' but blend_model_path does not exist: {path}")

    if tamp.get("blend_ops") and not tamp.get("blend_trajectory"):
        problems.append("blend_ops is set but blend_trajectory is not true, so no blending happens")

    for key in ("blend_pace", "blend_boundary_mode", "blend_flow_steps", "blend_flow_retime_only"):
        if key in tamp and str(tamp.get("blend_mode", "spline")).lower() != "flow":
            problems.append(f"{key} only applies when blend_mode is 'flow'; it is ignored here")
    if tamp.get("blend_vae_sample_target") and str(tamp.get("blend_mode", "spline")).lower() != "vae":
        problems.append("blend_vae_sample_target only applies when blend_mode is 'vae'; it is ignored here")

    # The knobs below are each read only behind another one, by the same resolve_* function that
    # reads the gate -- so set without it, they are accepted, passed on, and change nothing.
    retiming = bool(tamp.get("vae_retiming")) and bool(tamp.get("vae_manifold_weight"))
    if tamp.get("vae_retiming") and not retiming:
        problems.append(
            "vae_retiming is set but vae_manifold_weight is 0 or unset, so nothing would optimize the "
            "trajectory clock and the planner ignores vae_retiming"
        )
    for key in ("retime_scale", "retime_smooth_weight", "retime_limit_weight"):
        if key in tamp and not retiming:
            problems.append(f"{key} only applies when vae_retiming is on; it is ignored here")
    if retiming and tamp.get("blend_trajectory"):
        # Not a mistake -- the planner means it -- but it turns a whole blend_* block off, and the
        # planner's own warning about it lands in the sidecar log, not in front of anyone.
        problems.append(
            "vae_retiming gives the VAE cost the trajectory clock, so trajectory blending "
            "(blend_trajectory and every blend_* key) is switched off for every plan"
        )

    seeds = int(tamp.get("posture_selection_seeds") or 0)
    for key in ("posture_grasp_roll", "posture_ref", "posture_pos_tol", "posture_rot_tol"):
        if key in tamp and seeds <= 1:
            problems.append(f"{key} only applies when posture_selection_seeds is above 1; it is ignored here")
    if seeds > 1 and tamp.get("posture_ref"):
        # cuTAMP loads the prior at its first plan, well after warm-up.
        path = _resolve_asset(profile, str(tamp["posture_ref"]), "posture_ref", runtime_dir)
        if not path.is_file():
            problems.append(f"posture_selection_seeds is set but posture_ref does not exist: {path}")

    if "transit_apex_min_dist" in tamp and not tamp.get("transit_apex_height"):
        problems.append(
            "transit_apex_min_dist only applies when transit_apex_height is above 0; it is ignored here"
        )

    # Settings tiptop never reads (see options.GeminiSpec): kept so a profile can say which detector
    # labelled its data, and warned about when what they say is not what runs.
    gemini = o.perception.gemini
    if gemini.model != DETECTOR_MODEL:
        problems.append(
            f"perception.gemini.model is {gemini.model!r}, but the pinned tiptop always runs {DETECTOR_MODEL!r} "
            "(it takes no model from its config), so this changes nothing; set it to that"
        )
    if gemini.temperature is not None:
        problems.append(
            "perception.gemini.temperature is set, but the pinned tiptop calls its detector with its own "
            "default, so this changes nothing; set it to null"
        )

    # tandem's camera block asks only for the camera perception reads, which is right for teleop and
    # for another planner. The pinned tiptop opens BOTH of these at every warm-up (get_demo_container:
    # get_hand_camera(), get_external_camera()), whichever one perception reads, and the tiptop.yml
    # rendered here names only the cameras the profile has -- so a missing one is an OmegaConf
    # missing-key error tens of seconds into the warm-up.
    configured = profile.cameras.configured()
    for slot in ("hand", "external"):
        if slot not in configured:
            problems.append(
                f"{MISSING_CAMERA}{slot}: the pinned tiptop opens cameras.hand and cameras.external at every "
                "warm-up, whichever one perception reads"
            )

    missing = profiles.missing_calibration(profile)
    if missing:
        problems.append(
            f"{MISSING_EXTRINSICS} for serial(s) " + ", ".join(missing) + f" in {profile.calibration_file()}"
        )
    return problems


# --------------------------------------------------------------------------- environment


def render_env(
    profile: Profile,
    options: Any = None,
    *,
    events_file: Path,
    task: str | None = None,
    runtime_dir: Path | None = None,
    base: dict[str, str] | None = None,
) -> dict[str, str]:
    """The environment the planner backend's process runs in.

    Every name here is read by code in the planner's pinned tree; nothing is aspirational. tandem no longer
    spawns the planner's own CLI — it runs its own sidecar inside the same environment (see
    ``tandem.planners.tiptop``) — but that sidecar calls the same functions, which read the same
    variables.
    """
    env = dict(base if base is not None else os.environ)
    o = _options(profile, options)

    # First task; later ones are typed at the child's stdin prompt.
    env["TIPTOP_TASK"] = task or profile.goal_or_prompt()
    # Only set when the goal genuinely differs from the language label, so tiptop otherwise
    # records whatever task actually ran (which is what a session where the operator retypes
    # the task needs).
    goal = profile.task.goal
    if goal and profile.task.prompt and goal != profile.task.prompt:
        env["TIPTOP_INSTRUCTION"] = profile.task.prompt
    else:
        env.pop("TIPTOP_INSTRUCTION", None)

    env["TIPTOP_EVENTS_FILE"] = str(events_file)
    env["TIPTOP_STATE_PORT"] = str(o.robot.state_port)
    env["TIPTOP_CONFIG"] = str(_session_config_path(profile))
    env["TIPTOP_CALIBRATION"] = str(profile.calibration_file())
    # The source scoped per-robot data with DC_WORKSPACE and keyed extrinsics off it; a
    # tandem profile plays that role, and setting it keeps the planner's own
    # workspace-aware paths pointing somewhere sane.
    env["DC_WORKSPACE"] = profile.name
    env["TANDEM_PROFILE"] = profile.name

    # Camera serial overrides tiptop and droid both read.
    cams = profile.cameras.configured()
    for key, var in (
        ("hand", "TIPTOP_HAND_CAMERA_ID"),
        ("external", "TIPTOP_EXTERNAL_CAMERA_ID"),
        ("external_2", "TIPTOP_EXTERNAL_2_CAMERA_ID"),
    ):
        if key in cams:
            env[var] = cams[key].serial

    # google-genai's bare Client() reads either name; set both so it cannot miss. TiPToP's perception
    # needs it (its detector is Gemini), so a session with TiPToP refuses to start without one.
    key = secrets.gemini_api_key()
    if key:
        env["GEMINI_API_KEY"] = key
        env["GOOGLE_API_KEY"] = key

    # The cuRobo fork's VAE/RND costs default their checkpoints relative to what they assume
    # is a monorepo root. The runtime dir mirrors that layout, but set the env vars they also
    # honour so a relocated or profile-local checkpoint wins regardless.
    if runtime_dir is not None:
        vae = runtime_dir / "vae" / "checkpoints" / "vae_full_v2.pt"
        rnd = runtime_dir / "rnd" / "checkpoints" / "rnd_droid.pt"
        if vae.is_file():
            env.setdefault("VAE_MANIFOLD_CKPT", str(vae))
        if rnd.is_file():
            env.setdefault("RND_NOVELTY_CKPT", str(rnd))
    if o.tamp.get("vae_path"):
        env["VAE_MANIFOLD_CKPT"] = str(_resolve_asset(profile, str(o.tamp["vae_path"]), "vae_path", runtime_dir))

    # opencv's LAPACK and torch both drive one shared libmkl_core; the threaded path returns a
    # corrupt pivot array and cuRobo's get_stomp_cov() dies inside torch.inverse. Planning runs
    # on the GPU, so serialising MKL costs nothing that matters.
    env.setdefault("MKL_NUM_THREADS", "1")
    return env


def _session_config_path(profile: Profile) -> Path:
    return paths.session_scratch_dir() / profile.name / "tiptop.yml"


def prepare_session_files(
    profile: Profile, session_dir: Path, options: Any = None, *, runtime_dir: Path | None = None
) -> dict:
    """Materialise everything a session needs before the child is spawned, in the session's own directory.

    ``session_dir`` is the session's (``BackendContext.session_dir``): the session made it and owns
    it, so where it is is not this module's to work out. Returns ``{events_file, config_file,
    overrides_file, session_dir}``.
    """
    session_dir = Path(session_dir)
    session_dir.mkdir(parents=True, exist_ok=True)

    config_file = write_tiptop_config(profile, _session_config_path(profile), options)
    overrides_file = write_tamp_overrides(
        profile, session_dir / "curobo-overrides.json", options, runtime_dir=runtime_dir
    )

    events_file = session_dir / "events.jsonl"
    # Pre-create so the tailer can attach before the child writes its first line.
    events_file.touch()

    if not profile.calibration_file().is_file():
        raise ProfileError(
            f"Profile {profile.name!r} has no calibration file at {profile.calibration_file()}.",
            hint="Run `tandem profile create` again, or create the file with `{}` and calibrate.",
        )

    return {
        "session_dir": session_dir,
        "events_file": events_file,
        "config_file": config_file,
        "overrides_file": overrides_file,
    }
