"""Profile → the three things a tiptop subprocess actually consumes.

    render_tiptop_config(profile)   -> the YAML tiptop_cfg() loads   ($TIPTOP_CONFIG)
    render_tamp_overrides(profile)  -> the JSON --curobo-overrides reads
    render_env(profile, ...)        -> the environment the child runs in

Keeping this in one small, unit-testable module is deliberate: it is the seam where a
profile stops being tandem's concern and becomes tiptop's, and it is where "did my override
actually apply?" is decided.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from ruamel.yaml import YAML

from tandem.core import paths, profiles, secrets, tamp_keys
from tandem.core.errors import ProfileError
from tandem.core.profiles import Profile

_yaml = YAML()
_yaml.default_flow_style = False


# --------------------------------------------------------------------------- tiptop.yml


def render_tiptop_config(profile: Profile) -> dict:
    """The dict tiptop's ``tiptop_cfg()`` expects (robot / cameras / perception)."""
    p = profile
    cameras: dict[str, Any] = {"perception": p.cameras.perception}
    for key, cam in p.cameras.configured().items():
        cameras[key] = {
            "serial": cam.serial,
            "type": cam.type,
            "resolution": cam.resolution,
            "fps": cam.fps,
        }

    return {
        "robot": {
            "type": p.robot.type,
            "dof": p.robot.dof,
            "host": p.robot.host,
            "port": p.robot.port,
            "gripper_port": p.robot.gripper_port,
            "time_dilation_factor": p.robot.time_dilation_factor,
            "q_home": list(p.robot.q_home),
            "q_capture": list(p.robot.q_capture),
        },
        "cameras": cameras,
        "perception": {
            # Unused since depth comes from the ZED's hardware stereo, but tiptop still reads
            # the key, so it stays for config compatibility.
            "foundation_stereo": {"url": "http://localhost:1234"},
            "m2t2": {
                "url": p.perception.m2t2.url,
                "apply_bounds": p.perception.m2t2.apply_bounds,
            },
            "sam": {"mode": p.perception.sam_mode},
            "robot_mask_margin_m": p.perception.robot_mask_margin_m,
            "depth_trunc_m": p.perception.depth_trunc_m,
            "voxel_downsample_size": p.perception.voxel_downsample_size,
            "contact_threshold_m": p.perception.contact_threshold_m,
            "mask_erosion_pixels": p.perception.mask_erosion_pixels,
            "depth_smoothing": {"num_frames": p.perception.depth_smoothing_frames},
        },
    }


def write_tiptop_config(profile: Profile, dest: Path) -> Path:
    dest.parent.mkdir(parents=True, exist_ok=True)
    with dest.open("w") as fh:
        fh.write("# Generated by tandem from the profile — edits here are overwritten.\n")
        _yaml.dump(render_tiptop_config(profile), fh)
    return dest


# --------------------------------------------------------------------------- overrides


def render_tamp_overrides(profile: Profile, *, runtime_dir: Path | None = None) -> dict:
    """The flat dict handed to ``tiptop-run --curobo-overrides``.

    Path-valued knobs are resolved to absolute paths here rather than left for tiptop to
    interpret against a repo root, so "relative" means "relative to the profile" — the only
    reading a profile author can reasonably expect.
    """
    out: dict[str, Any] = dict(profile.tamp)
    for key in tamp_keys.PATH_KEYS:
        if key in out:
            out[key] = str(_resolve_asset(profile, str(out[key]), key, runtime_dir))
    return out


def _resolve_asset(profile: Profile, value: str, key: str, runtime_dir: Path | None) -> Path:
    """Resolve a checkpoint path: absolute wins, then the profile dir, then the runtime dir.

    The runtime dir is included because the vendored checkpoints live there under the same
    relative layout the source monorepo used (vae/checkpoints/..., rnd/checkpoints/...), so
    an imported legacy config keeps working unchanged.
    """
    candidate = Path(os.path.expanduser(value))
    if candidate.is_absolute():
        return candidate
    for base in filter(None, (profile.dir(), runtime_dir)):
        resolved = base / candidate
        if resolved.exists():
            return resolved.resolve()
    # Nothing on disk yet. Return the profile-relative interpretation so the error message
    # names the place the user most likely meant.
    return (profile.dir() / candidate).resolve()


def write_tamp_overrides(profile: Profile, dest: Path, *, runtime_dir: Path | None = None) -> Path | None:
    """Write the overrides JSON, or return None when the profile sets nothing.

    Returning None matters: passing an empty --curobo-overrides is not the same as passing
    none, and we want stock behaviour to be exactly stock.
    """
    overrides = render_tamp_overrides(profile, runtime_dir=runtime_dir)
    if not overrides:
        return None
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(overrides, indent=2, sort_keys=True) + "\n")
    return dest


def render_hitl_config(profile: Profile) -> dict:
    """The `hitl` block handed to ``tiptop-run --hitl-config``.

    Emitted whole rather than sparsely: the reader rejects unknown keys loudly (unlike the
    cost overrides, which drop them silently), so sending every field is safe and makes the
    JSON on disk a complete record of what the run was configured with.
    """
    data = profile.hitl.model_dump(mode="python")
    if data.get("cache_path"):
        # A relative cache path means "beside the profile", the same rule the checkpoint paths
        # follow — not "wherever the driver happened to be started from".
        data["cache_path"] = str(_resolve_asset(profile, str(data["cache_path"]), "cache_path", None))
    return data


def write_hitl_config(profile: Profile, dest: Path) -> Path | None:
    """Write the HITL JSON, or return None when phase planning is off.

    Returning None matters: with no --hitl-config the driver never imports the package at all,
    so a disabled run is not merely a run that skips the feature.
    """
    if not profile.hitl.enabled:
        return None
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(render_hitl_config(profile), indent=2, sort_keys=True) + "\n")
    return dest


def check_assets(profile: Profile, *, runtime_dir: Path | None = None) -> list[str]:
    """Problems that would only surface minutes into a warmed session. Cheap to check now.

    The VAE manifold cost torch.loads its checkpoint lazily, so a missing file does not fail
    until the first plan — after cuRobo, SAM2 and the cameras have all warmed up.
    """
    problems: list[str] = []
    tamp = profile.tamp

    if tamp.get("vae_manifold_weight") and tamp.get("vae_path"):
        path = _resolve_asset(profile, str(tamp["vae_path"]), "vae_path", runtime_dir)
        if not path.is_file():
            problems.append(f"vae_manifold_weight is set but vae_path does not exist: {path}")

    if str(tamp.get("blend_mode", "")).lower() == "flow":
        raw = tamp.get("blend_model_path")
        if raw:
            path = _resolve_asset(profile, str(raw), "blend_model_path", runtime_dir)
            if not path.is_file():
                problems.append(f"blend_mode is 'flow' but blend_model_path does not exist: {path}")

    if tamp.get("blend_ops") and not tamp.get("blend_trajectory"):
        problems.append("blend_ops is set but blend_trajectory is not true, so no blending happens")

    for key in ("blend_pace", "blend_boundary_mode", "blend_flow_steps", "blend_flow_retime_only"):
        if key in tamp and str(tamp.get("blend_mode", "spline")).lower() != "flow":
            problems.append(f"{key} only applies when blend_mode is 'flow'; it is ignored here")

    missing = profiles.missing_calibration(profile)
    if missing:
        problems.append(
            "no camera extrinsics for serial(s) " + ", ".join(missing) + f" in {profile.calibration_file()}"
        )
    return problems


# --------------------------------------------------------------------------- environment


def render_env(
    profile: Profile,
    *,
    events_file: Path,
    task: str | None = None,
    runtime_dir: Path | None = None,
    base: dict[str, str] | None = None,
) -> dict[str, str]:
    """The environment for a tiptop-run child.

    Every name here is read by code in the vendored tree; nothing is aspirational.
    """
    env = dict(base if base is not None else os.environ)

    # First task; later ones are typed at the child's stdin prompt.
    env["TIPTOP_TASK"] = task or profile.goal_or_prompt()
    # Only set when the goal genuinely differs from the language label, so tiptop otherwise
    # records whatever task actually ran (which is what a session where the operator retypes
    # the task needs).
    goal = profile.task.goal
    if goal and profile.task.prompt and goal != profile.task.prompt:
        env["TIPTOP_INSTRUCTION"] = profile.task.prompt
    else:
        env.pop("TIPTOP_INSTRUCTION", None)

    env["TIPTOP_EVENTS_FILE"] = str(events_file)
    env["TIPTOP_STATE_PORT"] = str(profile.robot.state_port)
    env["TIPTOP_CONFIG"] = str(_session_config_path(profile))
    env["TIPTOP_CALIBRATION"] = str(profile.calibration_file())
    # The source scoped per-robot data with DC_WORKSPACE and keyed extrinsics off it; a
    # tandem profile plays that role, and setting it keeps the vendored code's own
    # workspace-aware paths pointing somewhere sane.
    env["DC_WORKSPACE"] = profile.name
    env["TANDEM_PROFILE"] = profile.name

    # Camera serial overrides tiptop and droid both read.
    cams = profile.cameras.configured()
    for key, var in (
        ("hand", "TIPTOP_HAND_CAMERA_ID"),
        ("external", "TIPTOP_EXTERNAL_CAMERA_ID"),
        ("external_2", "TIPTOP_EXTERNAL_2_CAMERA_ID"),
    ):
        if key in cams:
            env[var] = cams[key].serial

    # google-genai's bare Client() reads either name; set both so it cannot miss.
    key = secrets.gemini_api_key()
    if key:
        env["GEMINI_API_KEY"] = key
        env["GOOGLE_API_KEY"] = key

    # The cuRobo fork's VAE/RND costs default their checkpoints relative to what they assume
    # is a monorepo root. The runtime dir mirrors that layout, but set the env vars they also
    # honour so a relocated or profile-local checkpoint wins regardless.
    if runtime_dir is not None:
        vae = runtime_dir / "vae" / "checkpoints" / "vae_full_v2.pt"
        rnd = runtime_dir / "rnd" / "checkpoints" / "rnd_droid.pt"
        if vae.is_file():
            env.setdefault("VAE_MANIFOLD_CKPT", str(vae))
        if rnd.is_file():
            env.setdefault("RND_NOVELTY_CKPT", str(rnd))
    if profile.tamp.get("vae_path"):
        env["VAE_MANIFOLD_CKPT"] = str(
            _resolve_asset(profile, str(profile.tamp["vae_path"]), "vae_path", runtime_dir)
        )

    # opencv's LAPACK and torch both drive one shared libmkl_core; the threaded path returns a
    # corrupt pivot array and cuRobo's get_stomp_cov() dies inside torch.inverse. Planning runs
    # on the GPU, so serialising MKL costs nothing that matters.
    env.setdefault("MKL_NUM_THREADS", "1")
    return env


def _session_config_path(profile: Profile) -> Path:
    return paths.session_scratch_dir() / profile.name / "tiptop.yml"


def prepare_session_files(profile: Profile, session_id: str, *, runtime_dir: Path | None = None) -> dict:
    """Materialise everything a session needs before the child is spawned.

    Returns ``{events_file, config_file, overrides_file, session_dir}``.
    """
    session_dir = paths.session_scratch_dir() / profile.name / session_id
    session_dir.mkdir(parents=True, exist_ok=True)

    config_file = write_tiptop_config(profile, _session_config_path(profile))
    overrides_file = write_tamp_overrides(profile, session_dir / "curobo-overrides.json", runtime_dir=runtime_dir)
    hitl_file = write_hitl_config(profile, session_dir / "hitl-config.json")

    events_file = session_dir / "events.jsonl"
    # Pre-create so the tailer can attach before the child writes its first line.
    events_file.touch()

    if not profile.calibration_file().is_file():
        raise ProfileError(
            f"Profile {profile.name!r} has no calibration file at {profile.calibration_file()}.",
            hint="Run `tandem profile create` again, or create the file with `{}` and calibrate.",
        )

    return {
        "session_dir": session_dir,
        "events_file": events_file,
        "config_file": config_file,
        "overrides_file": overrides_file,
        "hitl_file": hitl_file,
    }
